sudo: false
language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y redis-server memcached
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script: 
  - "composer install"

script: 
- "phpunit"